apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
%{ if contains(custom_tools, "kustomize_3_2_0") ~}
  kustomize.path.v3.2.0: /usr/local/bin/kustomize_3_2_0
%{ endif ~}
  repositories: |
    - name: cluster-repo
      url: ${app_repo}
    - name: ops-core
      url: ${system_repo}
%{ if additional_repositories != [] ~}
%{ for key in additional_repositories ~}
    - name: ${key.name}
      url: ${key.value}
%{ endfor ~}
%{ endif ~}
  repository.credentials: |
%{ if additional_credentials != "" ~}
    ${additional_credentials}
%{ else ~}
    - url: git@github.com:pepsico-ecommerce
      sshPrivateKeySecret:
        key: id_rsa
        name: argo-ci-git-ssh-key
%{ endif ~}
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $${dex.github.clientID}
          # secret value will be taken from environment variable of the dex container
          clientSecret: $${dex.github.clientSecret}
          orgs:
          - name: ${github_org}
            teams: ${github_teams}

  url: https://${domain_name}.${dns_zone}
  application.instanceLabelKey: argocd.argoproj.io/instance
  accounts.circleci: apiKey, login
