---
%{ if external_secret_type == "eso" &&  external_secret_eso_kind == "SecretStore" ~}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: ${external_secret_aws_role}
  name: ${app_name}-secret-store-sa
  namespace: ${namespace}
---
apiVersion: external-secrets.io/v1beta1
kind: ${external_secret_eso_kind}
metadata:
  name: ${external_secret_eso_kind_name}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: ${app_name}-secret-store-sa
%{ endif ~}
