%{ if external_secret_type == "kes" ~}
apiVersion: kubernetes-client.io/v1
%{ endif ~}
%{ if external_secret_type == "eso" ~}
apiVersion: external-secrets.io/v1beta1
%{ endif ~}
kind: ExternalSecret
metadata:
  name: argo-ci-git-ssh-key
spec:
%{ if external_secret_type == "kes" ~}
  backendType: secretsManager
%{ endif ~}
%{ if external_secret_type == "eso" ~}
  refreshInterval: 1m
  secretStoreRef:
    name: ${external_secret_eso_kind_name}
    kind: ${external_secret_eso_kind}
  target:
    creationPolicy: Owner
%{ endif ~}
%{ if external_secret_type == "kes" ~}
  data:
    - key: ${github_ssh_key_secret_name}
      name: id_rsa
%{ endif ~}
%{ if external_secret_type == "eso" ~}
  data:
    - secretKey: id_rsa
      remoteRef:
        key: ${github_ssh_key_secret_name}
%{ endif ~}
